name: message_app_frontend
description: A modern messaging client with industry-grade UI built with Flutter.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.1
  go_router: ^13.2.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.0.0
  socket_io_client: ^2.0.3
  image_picker: ^1.0.7
  video_player: ^2.8.6
  mime: ^1.0.5
  http_parser: ^4.0.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
